import Head from 'next/head'
import { Inter } from '@next/font/google'
import {motion as m} from 'framer-motion'
import {container,item} from '../animation'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <m.div initial={{y:'100%'}} animate={{y:'0%'}} transition={{duration:0.75, ease:"easeOut"}} exit={{opacity:1}} className=" text-gray-900 absolute top-0 left-0 w-full h-full bg-orange-100 lg:px-48 px-16">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <div className=' my-96 p-1'>
          <h1 className=' text-6xl text-center lg:text-right lg:text-9xl'>Happy Habesha</h1>
        </div>
        <div className=' flex justify-between'>
          <m.div variants={container} initial='hidden' animate='show'>
            <m.h2 variants={item}>Design </m.h2>
            <m.h2 variants={item}>Comapany </m.h2>
            <m.h2 variants={item}>2022 </m.h2>
          </m.div>
          <m.div variants={container} initial='hidden' animate='show'>
            <m.h3 variants={item}>This habesha gonna make you smile.</m.h3>
            <m.h3 variants={item}>Ethiopian designs to make you happy.</m.h3>
            <m.h3 variants={item}>Click contact for cool transition.</m.h3>
          </m.div>
        </div>
      </main>
    </m.div>
  )
}
